[user]
username = "lajbel"
email = "lajbelms@gmail.com"
discord = "lajbel#3662"

[records]
CNAME = "baf17f19-c9f3-4080-a8bc-7412f7365b90.id.repl.co"
TXT = "replit-verify=baf17f19-c9f3-4080-a8bc-7412f7365b90"
